name: SBOM

on:
  push:
    branches: [main]
  release:
    types: [created]

permissions:
  contents: write

jobs:
  sbom:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4

      - name: Generate SBOM
        uses: anchore/sbom-action@57aae528053a48a3f6235f2d9461b05fbcb7366d  # v0.23.1
        with:
          format: cyclonedx-json
          output-file: sbom.cyclonedx.json
          upload-artifact: true
          upload-release-assets: true

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02  # v4
        with:
          name: sbom
          path: sbom.cyclonedx.json
          retention-days: 90
